controllers:
    resource:
        path: ../../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute
    
phpmyadmin:
  path: /phpmyadmin
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: 'http://localhost/phpmyadmin'  # Ajusta la URL
    permanent: true