<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCoFsvVB\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCoFsvVB/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerCoFsvVB.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerCoFsvVB\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerCoFsvVB\App_KernelProdDebugContainer([
    'container.build_hash' => 'CoFsvVB',
    'container.build_id' => 'e51e59a9',
    'container.build_time' => 1741425548,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCoFsvVB');
