<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\RegistrationController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\RegistrationController::logout'], [], [['text', '/logout']], [], [], []],
    'app_homepage' => [[], ['_controller' => 'App\\Controller\\RegistrationController::homepage'], [], [['text', '/']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\RegistrationController::verifyUserEmail' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
    'App\Controller\RegistrationController::login' => [[], ['_controller' => 'App\\Controller\\RegistrationController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\RegistrationController::logout' => [[], ['_controller' => 'App\\Controller\\RegistrationController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\RegistrationController::homepage' => [[], ['_controller' => 'App\\Controller\\RegistrationController::homepage'], [], [['text', '/']], [], [], []],
];
