app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

app_login:
  path: /
  controller: App\Controller\RegistrationController::login

app_logout:
  path: /logout
  controller: App\Controller\RegistrationController::logout