<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhSdzGA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhSdzGA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXhSdzGA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXhSdzGA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXhSdzGA\App_KernelDevDebugContainer([
    'container.build_hash' => 'XhSdzGA',
    'container.build_id' => 'e50ab4cf',
    'container.build_time' => 1742639635,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhSdzGA');
