<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTl4Msqh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTl4Msqh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTl4Msqh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTl4Msqh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTl4Msqh\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tl4Msqh',
    'container.build_id' => 'e5df67ed',
    'container.build_time' => 1743004673,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTl4Msqh');
