<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXbRh4Fx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXbRh4Fx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXbRh4Fx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXbRh4Fx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXbRh4Fx\App_KernelDevDebugContainer([
    'container.build_hash' => 'XbRh4Fx',
    'container.build_id' => 'dcffad44',
    'container.build_time' => 1743431981,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXbRh4Fx');
