<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI2xuxnb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI2xuxnb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI2xuxnb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI2xuxnb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI2xuxnb\App_KernelDevDebugContainer([
    'container.build_hash' => 'I2xuxnb',
    'container.build_id' => '16e7411e',
    'container.build_time' => 1741424106,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI2xuxnb');
